---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/forum/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ecommerce/defaults/main.yml
    - roles/ecomworker/defaults/main.yml
  roles:
    # This install mysql and creates users.
    - role: edxlocal
    - role: memcache
    - role: mongo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - role: elasticsearch
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
